services:
  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.example
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/epitrello
      - CLIENT_URL=http://localhost:5173
    ports:
      - '5000:5000'
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000/api
    restart: unless-stopped
    ports:
      - '5173:80'
    depends_on:
      - backend

volumes:
  mongo-data:
